default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: <%= ENV['GAME_LFG_DATABASE_USERNAME'] %>
  password: <%= ENV['GAME_LFG_DATABASE_PASSWORD'] %>
  template: template1
  pool: 5

development:
  <<: *default
  database: game_lfg_development

test:
  <<: *default
  database: game_lfg_test

production:
  <<: *default
  database: game_lfg_production
